export const HousingData = [
    {
        type: "studio",
        area: 33,
        isFurnished: true,
        isRented: false,
        img: null,
        city: 'Saint-Omer',
        rent: '674€/mois',
    },
    {
        type: "T3",
        area: 80,
        isFurnished: true,
        isRented: true,
        img: null,
        city: 'Loos',
        rent: '520€/mois',
    },
    {
        type: "T3",
        area: 80,
        isFurnished: true,
        isRented: true,
        img: null,
        city: 'Loos',
        rent: '520€/mois',
    },
    {
        type: "T3",
        area: 80,
        isFurnished: true,
        isRented: true,
        img: null,
        city: 'Loos',
        rent: '520€/mois',
    },
    {
        type: "T3",
        area: 80,
        isFurnished: true,
        isRented: true,
        img: null,
        city: 'Loos',
        rent: '520€/mois',
    },
];